### ISSUE TITLE
Permission status undetermined on android 13

### ISSUE THREAD

**Issue by AliPunjabi** [svprdga/Adapt-Android-13#1]
I am trying your way but popup for asking notification permission is nott appearingg and I am getting undetermined on statusess

**Comment by svprdga** [comment]
Are you executing this project in a device running Android 13?

**Comment by AliPunjabi** [comment]
yes

**Comment by AliPunjabi** [comment]
even I open the app settings using open appsettings(); and allowed the app but still not getting notifications from firebase

**Comment by svprdga** [comment]
> even I open the app settings using open appsettings(); and allowed the app but still not getting notifications from firebase

What are you trying to do? To ask for permissions to show notifications, or to send a notification? It's two different things. 

In this project I show you the former only.

**Comment by AliPunjabi** [comment]
to show notifications
acttually I am gettig exception in flutter local notification plugin, you can check here:
https://github.com/MaikuB/flutter_local_notifications/issues/1896

**Comment by svprdga** [comment]
@AliPunjabi In order to request general assistance, I recommend that you go to the specific communities for this, for example [StackOverflow](https://stackoverflow.com/) or the [r/flutterhelp subreddit](https://www.reddit.com/r/flutterhelp/).

I'm going to close this issue as it looks like the problem you're having is unrelated to this project.
